### ISSUE TITLE
CDS on multiple kubernetes clusters

### ISSUE THREAD

**Issue by DoronCohen** [ovh/cds#4263]
Hi,

We are interested in CDS to replace our current CI / regression system. Our intention for now is to run multiple k8s clusters across multiple AWS regions and to run CDS core on one of them. The rest will only run hatcheries and will run jobs.

A few questions:
- Can I connect multiple hatcheries to one CDS core?
- Can I route a job to a specific hatchery? I know I can use requirements but I didnt see anything that can help in my case. Groups are not really helping because these are jobs from the same project.
- Can I view the hatcheries or name / tag them in the UI? Can I view what jobs are running on what hatcheries?

We are also unable to use it with all of our projects because we use bitbucket cloud (would love to see #4026 solved :wink:)

**Comment by yesnault** [comment]
_Can I connect multiple hatcheries to one CDS core?_
Yes, sure. You can have one CDS APi running, and used many hatcheries with it. Hatchery can be attached to k8s, docker swarm, openstack... all in the same time. So that, with one CDS API, you can use many k8s if you want.

_Can I route a job to a specific hatchery? I know I can use requirements but I didnt see anything that can help in my case. Groups are not really helping because these are jobs from the same project._
You can use many groups in one project. Each hatchery belongs to one group. A worker model belong to one group. You can use the job-prerequisite of type "model" to say CDS to use this or this worker model, so that, this or this hatchery.

_Can I view the hatcheries or name / tag them in the UI? Can I view what jobs are running on what hatcheries?_
It's in the "Information" section above a job.

**Comment by bnjjj** [comment]
By the way for the third question you can also view your current queue and so see in real time when your jobs are taken and by which hatchery.
On you-ui-domain/settings/queue or accessible via settings menu then "Current CDS jobs queue"

**Comment by DoronCohen** [comment]
Thanks for the quick and detailed answers. Dispatching by groups will do it for this case.
Is there any intention to support affinity in dispatching? something in the lines of https://www.nomadproject.io/docs/job-specification/affinity.html

**Comment by yesnault** [comment]
@DoronCohen yes, it's planned with https://github.com/ovh/cds/issues/1909
