### ISSUE TITLE
github oauth call back fails, and not able to connect to repo

### ISSUE THREAD

**Issue by snapbots** [ovh/cds#4301]
expect:
  - http://snap-github.ngrok.io.ngrok.io/repositories_manager/oauth2/callback
  per documentation for api server to succeed
actual:
  hook fails
  - manual insert code (workaround) for above issue
  - still can not see repository

please see recording:
```
https://cl.ly/e2b776313619
```

**Comment by bnjjj** [comment]
+ Is your client id and client secret right in your configuration ?
+ When you indicate the code. Was the request in success or not ?
+ Have you tried to click on the UI button (just near to place when you choose your repository in application/advanced view) to resynchronize all your repository list ?

**Comment by snapbots** [comment]
yes. updated with video capture of issue above. 
1) yes, I was able to work around it and see it in github (38th second in video)
2) UI looks good. which part of the code do you like to see
3) yes.  and it also failed. (last part of video)

**Comment by yesnault** [comment]
@snapbots thank for video, it's more easiest to debug.
So, the callback URL is wrong. In fact, when you click on the link, it's open github, then github redirect you on url http://cds3-cds-ui... instead of your real url for your UI (at 13")
this URL can be configured in the section `[api.url]`, attr `ui`

In fact, when you go on your project, you can see the repository manager github configured.

Then, second error: on your application, you should link the repo to your git repository. Seems does not work. Do you have an error on the service `vcs` when you click on `resynchronize`?

Last question, which browser do you use? according to the video, there seems to be some css problem on this browser.

**Comment by sguiheux** [comment]
Close for inactivity
