### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by wychl** [ovh/cds#4391]
Starting step "/GitClone-1"
Executing: git clone --depth 50 --branch master --recursive ...  

Executing: git reset --hard f2ebcdd807f303ccb27cc766098d0291c56eb779
Cloning into '/tmp/9c4905c613266517/Z2l0/run'...
Could not create directory '/nonexistent/.ssh'.
Failed to add the host to the list of known hosts (/nonexistent/.ssh/known_hosts).
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unable to git clone: Command fail: 128
End of step "/GitClone-1" [Fail] with reason: Unable to git clone: Command fail: 128

**Comment by yesnault** [comment]
Seems that worker don't have the right to create the .ssh directory in your worker model.

Is your worker model a public docker image available somewhere? If yes, we can investigate on it. Otherwise, you can configure the basedir of the worker with the flag `--basedir`. You can customize it on the `cmd` attribute on the worker model page.
