### ISSUE TITLE
Conditional environments in template

### ISSUE THREAD

**Issue by marie-j** [ovh/cds#5759]
Hello, 

Currently it is not possible to create environments depending on the template parameters whether it is generating from a loop or having conditions

For example if I have something like:
```yaml
[[if .params.createEnvironment ]]
# Environment specific configuration
name: conditional-environment 
[[end]]
```
It generates an error if .params.createEnvironment equals false when applying a template as environment name is undefined

Could it make sense to add this option ?

**Comment by richardlt** [comment]
Hi, you're right. If there is an environment defined in the template even if it's empty, CDS will expect it to be valid. Maybe we can imagine to skip empty file for sure.
But for now you can also remove the condition and always define the environment because if this environment is not used in the workflow definition it should be ignored and not created in CDS when applying the template. In another words you can use a condition inside the workflow definition to disable/enable the usage of this env.

**Comment by marie-j** [comment]
@richardlt I just tried this out and the environment is still created even though not used, it is just not linked to any element in the workflow

**Comment by richardlt** [comment]
Ok my bad, env will be imported even if not used by the workflow.
So I created a PR to skip empty files from template :)
